### ISSUE TITLE
Doesn't work in Linux console

### ISSUE THREAD

**Issue by blakemcbride** [TieDyedDevil/akt#1]
Greetings!

I use akt all of the time under X.  However, it doesn't seem to work under Linux console (without X).  Could it be made to?

Thanks!

Blake McBride

**Comment by TieDyedDevil** [comment]
Hi Blake,

Please provide details (to start: system, version, invocation and symptoms).

akt does work in Fedora's console; I've used it on several occasions.

**Comment by blakemcbride** [comment]
I discovered it on a Raspberry PI running Debian Linux.  While trying it again to answer all of your questions, it worked perfectly.  So it runs great on a Raspberry PI.

I think my problem must have been when I was first attempting to get it to work.  I was likely doing stuff with loadkeys before attempting akt.  That somehow messed up my environment that required a re-boot to correct.

No akt works great everywhere, even on a Raspberry PI!  Great utility.

Thanks, and sorry for the trouble.

Blake

**Comment by TieDyedDevil** [comment]
No worries, Blake. Thanks for the update.
